### ISSUE TITLE
XCode 11 issue

### ISSUE THREAD

**Issue by altaisukh** [TeamHive/capacitor-single-sign-on#9]
After upgrading XCode to 11, SingleSignOn fails in builds and in the simulator without much detail regarding the error. 

Now getting the following error from SingleSignOn:

```
ERROR MESSAGE:  {"message":"","errorMessage":""}
```

**Comment by nedvisol** [comment]
This is because in iOS 13, ASWebAuthenticationSession requires presentationContextProvider to be set. I made a PR to fix this issue:
https://github.com/TeamHive/capacitor-single-sign-on/pull/10

@sbannigan

**Comment by sbannigan** [comment]
fixed in `4.0.0`
